// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef TestOne_h
#define TestOne_h
#include <FL/Fl.H>
#include <stdio.h>
#include <stdlib.h>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Output.H>
extern Fl_Input* test_input;
extern Fl_Output* test_output;
#include "truncstruct.hpp"
#endif

